import { Emotion } from "./types";

const emotions: Emotion[] = [
  {
    id: "positive",
    nameEN: "Positive",
    nameES: "Positivo",
    nameCZ: "Pozitivní",
    emotions: [
      {
        id: "positivity",
        nameEN: "Positividad",
        nameES: "Positividad",
        nameCZ: "Pozitivita",
        emotions: [
          {
            id: "grateful",
            nameEN: "Grateful",
            nameES: "Agradecido",
            nameCZ: "Vděčný",
          },
          {
            id: "joyful",
            nameEN: "Joyful",
            nameES: "Alegre",
            nameCZ: "Radostný",
          },
          {
            id: "calm",
            nameEN: "Calm",
            nameES: "Apacible",
            nameCZ: "Klidný",
          },
          {
            id: "enthusiastic",
            nameEN: "Enthusiastic",
            nameES: "Entusiasmado",
            nameCZ: "Ochotný",
          },
          {
            id: "curious",
            nameEN: "Curious",
            nameES: "Curioso",
            nameCZ: "Zvědavý",
          },
          {
            id: "confident",
            nameEN: "Confident",
            nameES: "Confiado",
            nameCZ: "Sebevědomý",
          },
          {
            id: "compassionate",
            nameEN: "Compassionate",
            nameES: "Compasivo",
            nameCZ: "Soucitný",
          },
          {
            id: "optimistic",
            nameEN: "Optimistic",
            nameES: "Optimista",
            nameCZ: "Optimistický",
          },
          {
            id: "vitality",
            nameEN: "Vitality",
            nameES: "Vitalidad",
            nameCZ: "Vitalita",
          },
        ],
      },
      {
        id: "gratitude",
        nameEN: "Gratitud",
        nameES: "Gratitud",
        nameCZ: "Vděčnost",
        emotions: [
          {
            id: "fortunate",
            nameEN: "Fortunate",
            nameES: "Afortunado",
            nameCZ: "Šťastný",
          },
          {
            id: "thankful",
            nameEN: "Thankful",
            nameES: "Agradecido",
            nameCZ: "Vděčný",
          },
        ],
      },
      {
        id: "joy",
        nameEN: "Alegría",
        nameES: "Alegría",
        nameCZ: "Radost",
        emotions: [
          {
            id: "cheerful",
            nameEN: "Cheerful",
            nameES: "Alegre",
            nameCZ: "Radostný",
          },
          {
            id: "animated",
            nameEN: "Animated",
            nameES: "Animado",
            nameCZ: "Oživený",
          },
          {
            id: "blissful",
            nameEN: "Blissful",
            nameES: "Dichoso",
            nameCZ: "Blahodárný",
          },
          {
            id: "ecstatic",
            nameEN: "Ecstatic",
            nameES: "Emocionado",
            nameCZ: "Extatický",
          },
          {
            id: "exuberant",
            nameEN: "Exuberant",
            nameES: "Exuberante",
            nameCZ: "Přebytečný",
          },
          {
            id: "elated",
            nameEN: "Elated",
            nameES: "Exultante",
            nameCZ: "Vzrušený",
          },
          {
            id: "jovial",
            nameEN: "Jovial",
            nameES: "Jovial",
            nameCZ: "Jovialní",
          },
          {
            id: "joyous",
            nameEN: "Joyous",
            nameES: "Gozoso",
            nameCZ: "Radostný",
          },
          {
            id: "delighted",
            nameEN: "Delighted",
            nameES: "Maravillado",
            nameCZ: "Potěšený",
          },
          {
            id: "exhilarated",
            nameEN: "Exhilarated",
            nameES: "Exaltado",
            nameCZ: "Osvěžený",
          },
          {
            id: "exultant",
            nameEN: "Exultant",
            nameES: "Exultante",
            nameCZ: "Exultující",
          },
          {
            id: "radiant",
            nameEN: "Radiant",
            nameES: "Radiante",
            nameCZ: "Zářící",
          },
        ],
      },
      {
        id: "calmness",
        nameEN: "Calma",
        nameES: "Calma",
        nameCZ: "Klid",
        emotions: [
          {
            id: "relieved",
            nameEN: "Relieved",
            nameES: "Aliviado",
            nameCZ: "Ulevilo",
          },
          {
            id: "serene",
            nameEN: "Serene",
            nameES: "Sosegado",
            nameCZ: "Klidný",
          },
          {
            id: "peaceful",
            nameEN: "Peaceful",
            nameES: "Apacible",
            nameCZ: "Klidný",
          },
          {
            id: "comfortable",
            nameEN: "Comfortable",
            nameES: "Cómodo",
            nameCZ: "Pohodlný",
          },
          {
            id: "tranquil",
            nameEN: "Tranquil",
            nameES: "Tranquilo",
            nameCZ: "Klidný",
          },
          {
            id: "soothing",
            nameEN: "Soothing",
            nameES: "Sosegado",
            nameCZ: "Uklidňující",
          },
        ],
      },
      {
        id: "enthusiasm",
        nameEN: "Entusiasmo",
        nameES: "Entusiasmo",
        nameCZ: "Nadšení",
        emotions: [
          {
            id: "passionate",
            nameEN: "Passionate",
            nameES: "Apasionado",
            nameCZ: "Vášnivý",
          },
          {
            id: "excited",
            nameEN: "Excited",
            nameES: "Emocionado",
            nameCZ: "Vzrušený",
          },
          {
            id: "eager",
            nameEN: "Eager",
            nameES: "Emprendedor",
            nameCZ: "Dychtivý",
          },
          {
            id: "energetic",
            nameEN: "Energetic",
            nameES: "Enérgico",
            nameCZ: "Energetický",
          },
          {
            id: "inspired",
            nameEN: "Inspired",
            nameES: "Inspirado",
            nameCZ: "Inspirativní",
          },
          {
            id: "motivated",
            nameEN: "Motivated",
            nameES: "Motivado",
            nameCZ: "Motivovaný",
          },
        ],
      },
      {
        id: "curiosity",
        nameEN: "Curiosidad",
        nameES: "Curiosidad",
        nameCZ: "Zvědavost",
        emotions: [
          {
            id: "intrigued",
            nameEN: "Intrigued",
            nameES: "Intrigado",
            nameCZ: "Zvědavý",
          },
          {
            id: "interested",
            nameEN: "Interested",
            nameES: "Interesado",
            nameCZ: "Zaujatý",
          },
        ],
      },
      {
        id: "confidence",
        nameEN: "Confianza",
        nameES: "Confianza",
        nameCZ: "Důvěra",
        emotions: [
          {
            id: "bold",
            nameEN: "Bold",
            nameES: "Audaz",
            nameCZ: "Smělý",
          },
          {
            id: "capable",
            nameEN: "Capable",
            nameES: "Capaz",
            nameCZ: "Schopný",
          },
          {
            id: "confident",
            nameEN: "Confident",
            nameES: "Confiado",
            nameCZ: "Sebevědomý",
          },
          {
            id: "competent",
            nameEN: "Competent",
            nameES: "Competente",
            nameCZ: "Kompetentní",
          },
          {
            id: "assured",
            nameEN: "Assured",
            nameES: "Seguro",
            nameCZ: "Odpovědný",
          },
          {
            id: "self-assured",
            nameEN: "Self-assured",
            nameES: "Seguro de sí mismo",
            nameCZ: "Sebejistý",
          },
        ],
      },
      {
        id: "compassion",
        nameEN: "Compasión",
        nameES: "Compasión",
        nameCZ: "Soucit",
        emotions: [
          {
            id: "compassionate",
            nameEN: "Compassionate",
            nameES: "Compasivo",
            nameCZ: "Soucitný",
          },
          {
            id: "kind",
            nameEN: "Kind",
            nameES: "Benévolo",
            nameCZ: "Laskavý",
          },
          {
            id: "tender",
            nameEN: "Tender",
            nameES: "Tierno",
            nameCZ: "Jemný",
          },
          {
            id: "generous",
            nameEN: "Generous",
            nameES: "Generoso",
            nameCZ: "Štědrý",
          },
        ],
      },
      {
        id: "optimism",
        nameEN: "Optimismo",
        nameES: "Optimismo",
        nameCZ: "Optimismus",
        emotions: [
          {
            id: "optimistic",
            nameEN: "Optimistic",
            nameES: "Optimista",
            nameCZ: "Optimistický",
          },
          {
            id: "hopeful",
            nameEN: "Hopeful",
            nameES: "Esperanzado",
            nameCZ: "Plný naděje",
          },
          {
            id: "confident",
            nameEN: "Confident",
            nameES: "Seguro",
            nameCZ: "Sebevědomý",
          },
          {
            id: "positive",
            nameEN: "Positive",
            nameES: "Positivo",
            nameCZ: "Kladný",
          },
          {
            id: "upbeat",
            nameEN: "Upbeat",
            nameES: "Optimista",
            nameCZ: "Veselý",
          },
          {
            id: "encouraged",
            nameEN: "Encouraged",
            nameES: "Animado",
            nameCZ: "Odhodlaný",
          },
        ],
      },
      {
        id: "vitality",
        nameEN: "Vitalidad",
        nameES: "Vitalidad",
        nameCZ: "Vitalita",
        emotions: [
          {
            id: "active",
            nameEN: "Active",
            nameES: "Activo",
            nameCZ: "Aktivní",
          },
          {
            id: "lively",
            nameEN: "Lively",
            nameES: "Animado",
            nameCZ: "Oživený",
          },
          {
            id: "energetic",
            nameEN: "Energetic",
            nameES: "Enérgico",
            nameCZ: "Energetický",
          },
          {
            id: "strong",
            nameEN: "Strong",
            nameES: "Fuerte",
            nameCZ: "Silný",
          },
          {
            id: "vigorous",
            nameEN: "Vigorous",
            nameES: "Vigoroso",
            nameCZ: "Vigorózní",
          },
          {
            id: "alive",
            nameEN: "Alive",
            nameES: "Vivo",
            nameCZ: "Živý",
          },
        ],
      },
    ],
  },
  {
    id: "negative",
    nameEN: "Negative",
    nameES: "Negativo",
    nameCZ: "Negativní",
    emotions: [
      {
        id: "fear",
        nameEN: "Fear",
        nameES: "Miedo",
        nameCZ: "Strach",
        emotions: [
          {
            id: "afraid",
            nameEN: "Afraid",
            nameES: "Asustado",
            nameCZ: "Vyděšený",
          },
          {
            id: "anxious",
            nameEN: "Anxious",
            nameES: "Ansioso",
            nameCZ: "Úzkostlivý",
          },
          {
            id: "nervous",
            nameEN: "Nervous",
            nameES: "Nervioso",
            nameCZ: "Nervózní",
          },
          {
            id: "scared",
            nameEN: "Scared",
            nameES: "Asustado",
            nameCZ: "Vyděšený",
          },
          {
            id: "terrified",
            nameEN: "Terrified",
            nameES: "Aterrorizado",
            nameCZ: "Vyděšený",
          },
          {
            id: "worried",
            nameEN: "Worried",
            nameES: "Preocupado",
            nameCZ: "Ustaraný",
          },
          {
            id: "paranoid",
            nameEN: "Paranoid",
            nameES: "Paranoico",
            nameCZ: "Paranoidní",
          },
          {
            id: "insecure",
            nameEN: "Insecure",
            nameES: "Inseguro",
            nameCZ: "Nesmělý",
          },
          {
            id: "frightened",
            nameEN: "Frightened",
            nameES: "Asustado",
            nameCZ: "Vyděšený",
          },
          {
            id: "helpless",
            nameEN: "Helpless",
            nameES: "Impotente",
            nameCZ: "Bezmocný",
          },
        ],
      },
      {
        id: "sadness",
        nameEN: "Sadness",
        nameES: "Tristeza",
        nameCZ: "Smutek",
        emotions: [
          {
            id: "depressed",
            nameEN: "Depressed",
            nameES: "Deprimido",
            nameCZ: "Depresivní",
          },
          {
            id: "disappointed",
            nameEN: "Disappointed",
            nameES: "Decepcionado",
            nameCZ: "Zklamaný",
          },
          {
            id: "grief",
            nameEN: "Grief",
            nameES: "Dolor",
            nameCZ: "Zármutek",
          },
          {
            id: "heartbroken",
            nameEN: "Heartbroken",
            nameES: "Destrozado",
            nameCZ: "Zlomený srdce",
          },
          {
            id: "melancholic",
            nameEN: "Melancholic",
            nameES: "Melancólico",
            nameCZ: "Melancholický",
          },
          {
            id: "miserable",
            nameEN: "Miserable",
            nameES: "Miserable",
            nameCZ: "Bídný",
          },
          {
            id: "sad",
            nameEN: "Sad",
            nameES: "Triste",
            nameCZ: "Smutný",
          },
          {
            id: "sorrowful",
            nameEN: "Sorrowful",
            nameES: "Dolorido",
            nameCZ: "Ubohý",
          },
          {
            id: "unhappy",
            nameEN: "Unhappy",
            nameES: "Infeliz",
            nameCZ: "Nespokojený",
          },
          {
            id: "heartache",
            nameEN: "Heartache",
            nameES: "Dolor de corazón",
            nameCZ: "Bolest srdce",
          },
        ],
      },
      {
        id: "anger",
        nameEN: "Anger",
        nameES: "Ira",
        nameCZ: "Hněv",
        emotions: [
          {
            id: "angry",
            nameEN: "Angry",
            nameES: "Enojado",
            nameCZ: "Naštvaný",
          },
          {
            id: "annoyed",
            nameEN: "Annoyed",
            nameES: "Molesto",
            nameCZ: "Nervózní",
          },
          {
            id: "enraged",
            nameEN: "Enraged",
            nameES: "Enfurecido",
            nameCZ: "Rozzlobený",
          },
          {
            id: "frustrated",
            nameEN: "Frustrated",
            nameES: "Frustrado",
            nameCZ: "Frustrující",
          },
          {
            id: "irritated",
            nameEN: "Irritated",
            nameES: "Irritado",
            nameCZ: "Iritovaný",
          },
          {
            id: "outraged",
            nameEN: "Outraged",
            nameES: "Indignado",
            nameCZ: "Pohoršený",
          },
          {
            id: "resentful",
            nameEN: "Resentful",
            nameES: "Resentido",
            nameCZ: "Nahneván",
          },
          {
            id: "aggressive",
            nameEN: "Aggressive",
            nameES: "Agresivo",
            nameCZ: "Agresivní",
          },
          {
            id: "furious",
            nameEN: "Furious",
            nameES: "Furioso",
            nameCZ: "Vzteklý",
          },
          {
            id: "hostile",
            nameEN: "Hostile",
            nameES: "Hostil",
            nameCZ: "Nepřátelský",
          },
        ],
      },
      {
        id: "disgust",
        nameEN: "Disgust",
        nameES: "Asco",
        nameCZ: "Odpad",
        emotions: [
          {
            id: "disgusted",
            nameEN: "Disgusted",
            nameES: "Asqueado",
            nameCZ: "Odporný",
          },
          {
            id: "contempt",
            nameEN: "Contempt",
            nameES: "Desprecio",
            nameCZ: "Pohrdání",
          },
          {
            id: "revolted",
            nameEN: "Revolted",
            nameES: "Indignado",
            nameCZ: "Pobouřený",
          },
          {
            id: "repulsed",
            nameEN: "Repulsed",
            nameES: "Repugnado",
            nameCZ: "Znechucený",
          },
          {
            id: "nauseated",
            nameEN: "Nauseated",
            nameES: "Nauseabundo",
            nameCZ: "Nevolný",
          },
          {
            id: "disdain",
            nameEN: "Disdain",
            nameES: "Desprecio",
            nameCZ: "Pohrdání",
          },
          {
            id: "abhorrence",
            nameEN: "Abhorrence",
            nameES: "Aborrecimiento",
            nameCZ: "Odmítání",
          },
          {
            id: "detest",
            nameEN: "Detest",
            nameES: "Detestar",
            nameCZ: "Nesnášet",
          },
          {
            id: "sickened",
            nameEN: "Sickened",
            nameES: "Enfermo",
            nameCZ: "Nemocný",
          },
          {
            id: "repelled",
            nameEN: "Repelled",
            nameES: "Repelido",
            nameCZ: "Odpuzený",
          },
        ],
      },
      {
        id: "stress",
        nameEN: "Stress",
        nameES: "Estrés",
        nameCZ: "Stres",
        emotions: [
          {
            id: "stressed",
            nameEN: "Stressed",
            nameES: "Estresado",
            nameCZ: "Stresovaný",
          },
          {
            id: "overwhelmed",
            nameEN: "Overwhelmed",
            nameES: "Abrumado",
            nameCZ: "Přemáhaný",
          },
          {
            id: "burned-out",
            nameEN: "Burned out",
            nameES: "Quemado",
            nameCZ: "Vyhořelý",
          },
          {
            id: "tense",
            nameEN: "Tense",
            nameES: "Tenso",
            nameCZ: "Napjatý",
          },
          {
            id: "anxious",
            nameEN: "Anxious",
            nameES: "Ansioso",
            nameCZ: "Úzkostlivý",
          },
          {
            id: "pressured",
            nameEN: "Pressured",
            nameES: "Presionado",
            nameCZ: "Pod tlakem",
          },
          {
            id: "burdened",
            nameEN: "Burdened",
            nameES: "Atrapado",
            nameCZ: "Zatížený",
          },
          {
            id: "exhausted",
            nameEN: "Exhausted",
            nameES: "Agotado",
            nameCZ: "Vyčerpaný",
          },
          {
            id: "worried",
            nameEN: "Worried",
            nameES: "Preocupado",
            nameCZ: "Ustaraný",
          },
          {
            id: "nervous",
            nameEN: "Nervous",
            nameES: "Nervioso",
            nameCZ: "Nervózní",
          },
        ],
      },
    ],
  },
];

export default emotions;
